/**
 * Classify text into risk scores
 * Will take text and classify it via risk  
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigLanguage } from './configLanguage';
import { HttpsapiSwaggerhubComapistwohatshared200componentsschemasClientId } from './httpsapiSwaggerhubComapistwohatshared200componentsschemasClientId';

/**
 * Config options that can be sent into the classifier
 */
export interface ConfigTextClassifier { 
    /**
     * The sift system allows you to inherit the rules of another client.  By default the sift team has the largest most curitated list of rules so the default is everyone inherits from Sift which is client 0.  However if you have an enterprise plus package with multiple subproducts you can inherit from yourparentId,0.  You can also use this to follow certain domains such as gaming, familysafe, professional. 
     */
    inheritanceChain?: Array<HttpsapiSwaggerhubComapistwohatshared200componentsschemasClientId>;
    language?: ConfigLanguage;
}