/**
 * Classify text into risk scores
 * Will take text and classify it via risk  
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HttpsapiSwaggerhubComapistwohatshared200componentsschemasTopics } from './httpsapiSwaggerhubComapistwohatshared200componentsschemasTopics';
import { RedactedTextField } from './redactedTextField';

/**
 * Which parts of the text failed the filter.
 */
export interface FailingFragment { 
    /**
     * the text that failed
     */
    text?: string;
    /**
     * the simplified (normalized) form typically without caps.  This is typically the rule that matched.
     */
    normalized?: string;
    redactedText?: RedactedTextField;
    topics?: HttpsapiSwaggerhubComapistwohatshared200componentsschemasTopics;
    /**
     * The number of characters in the original text that this appears with an offset of 0
     */
    startPos?: number;
    /**
     * the number of characters where it ends
     */
    endPos?: number;
}