/**
 * Classify text into risk scores
 * Will take text and classify it via risk  
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * What was said in the last few messages before this message that did not fail the filter.  We use this to check for vertical chat where someone says you on one line and suck on the next to get around the filter.
 */
export type PreField = string;