/**
 * Classify text into risk scores
 * Will take text and classify it via risk
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConfigTextClassifier } from './configTextClassifier';
import { Rule } from './rule';
import { ClientId } from './clientId';
import { LanguageCode } from './languageCode';
import { PreField } from './preField';
import { TextField } from './textField';

export interface TextInput {
    clientId: ClientId;
    /**
     * What kind of UGC are you classifiying
     */
    contentType?: TextInput.ContentTypeEnum;
    language: LanguageCode;
    text: TextField;
    pre?: PreField;
    config?: ConfigTextClassifier;
    /**
     * Pass in potential rules so you can test the impact to the system
     */
    testRules?: Array<Rule>;
}
export namespace TextInput {
    export type ContentTypeEnum = 'SHORT_TEXT' | 'LONG_TEXT' | 'USERNAME';
    export const ContentTypeEnum = {
        SHORTTEXT: 'SHORT_TEXT' as ContentTypeEnum,
        LONGTEXT: 'LONG_TEXT' as ContentTypeEnum,
        USERNAME: 'USERNAME' as ContentTypeEnum
    };
}