/**
 * Shared Components
 * Used to share components between specification docs
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Unixtimestamp (milliseconds since Epoch)
 */
export type Timestamp = number;