/**
 * Shared Components
 * Used to share components between specification docs
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@twohat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Our system classifies text, images, video into standardized risk topics. Instead of a traditional system that returns good or bad we rate each topic on a cross-industry standard of 0 to 7.  The lowest number 0 means it is really clean or there is no risk of this topic detected.  4 typically means spelling mistake, 5 mild, 6 bad, and 7 is typically extreme.  Note that not all topics are bad some like Site Specific Terms can be positive.
 */
export interface Topics {
  /**
   * General Risk
   */
  _0?: number;
  /**
   * Bullying
   */
  _1?: number;
  /**
   * Fighting
   */
  _2?: number;
  /**
   * PII
   */
  _3?: number;
  /**
   * Dating and Sexting
   */
  _4?: number;
  /**
   * Vulgar
   */
  _5?: number;
  /**
   * Drugs and Alcohol
   */
  _6?: number;
  /**
   * Site Specific Terms
   */
  _7?: number;
  /**
   * Alarm
   */
  _8?: number;
  /**
   * Fraud
   */
  _9?: number;
  /**
   * Racist
   */
  _10?: number;
  /**
   * Religion
   */
  _11?: number;
  /**
   * Website
   */
  _13?: number;
  /**
   * Grooming
   */
  _14?: number;
  /**
   * Public Threats
   */
  _15?: number;
  /**
   * Real Name
   */
  _16?: number;
  /**
   * Terrorist Recruitment
   */
  _17?: number;
  /**
   * Subversive
   */
  _18?: number;
  /**
   * Sentiment
   */
  _19?: number;
  /**
   * Politics
   */
  _20?: number;
  /**
   * Custom1
   */
  _27?: number;
  /**
   * Custom2
   */
  _28?: number;
  /**
   * Custom3
   */
  _29?: number;
  /**
   * Custom4
   */
  _30?: number;
  /**
   * Custom5
   */
  _31?: number;
}